// Fichier centralisé pour les données des éleveurs
export const FARMERS_DATA = {
  1: {
    id: "1",
    name: "Jean Dupont",
    location: "Bordeaux, France",
    email: "jean.dupont@example.com",
    phone: "+33 6 12 34 56 78",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    joinDate: "15 Mars 2022",
    farm: {
      name: "Ferme des Chênes",
      size: "45 hectares",
      address: "123 Route de Campagne, 33000 Bordeaux",
      coordinates: { lat: 44.837789, lng: -0.57918 },
    },
    stats: {
      animals: 45,
      belts: 12,
      activeMonitoring: 38,
      healthAlerts: 2,
    },
    performance: {
      healthScore: 92,
      reproductionRate: 87,
      feedEfficiency: 78,
      overallRating: 4.5,
    },
    recentActivity: [
      {
        id: "a1",
        date: "Aujourd'hui, 10:45",
        action: "Ajout de 3 nouveaux animaux",
        icon: "plus-circle",
      },
      {
        id: "a2",
        date: "Hier, 14:30",
        action: "Alerte santé résolue",
        icon: "check-circle",
      },
      {
        id: "a3",
        date: "23 Avril, 09:15",
        action: "Maintenance des ceintures",
        icon: "tool",
      },
    ],
    animals: [
      {
        id: "an1",
        tag: "BV-2345",
        type: "Vache",
        age: "4 ans",
        status: "Sain",
      },
      {
        id: "an2",
        tag: "BV-2346",
        type: "Taureau",
        age: "5 ans",
        status: "Sain",
      },
      {
        id: "an3",
        tag: "BV-2347",
        type: "Vache",
        age: "3 ans",
        status: "Surveillance",
      },
    ],
  },
  2: {
    id: "2",
    name: "Marie Laurent",
    location: "Lyon, France",
    email: "marie.laurent@example.com",
    phone: "+33 6 23 45 67 89",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    joinDate: "3 Janvier 2021",
    farm: {
      name: "Ferme du Soleil",
      size: "78 hectares",
      address: "456 Chemin des Vignes, 69000 Lyon",
      coordinates: { lat: 45.764043, lng: 4.835659 },
    },
    stats: {
      animals: 78,
      belts: 24,
      activeMonitoring: 65,
      healthAlerts: 0,
    },
    performance: {
      healthScore: 96,
      reproductionRate: 92,
      feedEfficiency: 85,
      overallRating: 5,
    },
    recentActivity: [
      {
        id: "a1",
        date: "Aujourd'hui, 08:30",
        action: "Mise à jour des ceintures",
        icon: "refresh-cw",
      },
      {
        id: "a2",
        date: "Hier, 16:45",
        action: "Nouvel animal enregistré",
        icon: "plus-circle",
      },
      {
        id: "a3",
        date: "20 Avril, 11:20",
        action: "Rapport mensuel généré",
        icon: "file-text",
      },
    ],
    animals: [
      {
        id: "an1",
        tag: "BV-5678",
        type: "Vache",
        age: "3 ans",
        status: "Sain",
      },
      {
        id: "an2",
        tag: "BV-5679",
        type: "Vache",
        age: "6 ans",
        status: "Sain",
      },
      {
        id: "an3",
        tag: "BV-5680",
        type: "Taureau",
        age: "4 ans",
        status: "Sain",
      },
    ],
  },
  3: {
    id: "3",
    name: "Pierre Martin",
    location: "Toulouse, France",
    email: "pierre.martin@example.com",
    phone: "+33 6 34 56 78 90",
    image: "https://randomuser.me/api/portraits/men/67.jpg",
    joinDate: "27 Juin 2022",
    farm: {
      name: "Élevage du Sud",
      size: "32 hectares",
      address: "789 Avenue des Pyrénées, 31000 Toulouse",
      coordinates: { lat: 43.604652, lng: 1.444209 },
    },
    stats: {
      animals: 32,
      belts: 8,
      activeMonitoring: 25,
      healthAlerts: 3,
    },
    performance: {
      healthScore: 78,
      reproductionRate: 65,
      feedEfficiency: 72,
      overallRating: 3.5,
    },
    recentActivity: [
      {
        id: "a1",
        date: "Hier, 09:15",
        action: "Alerte santé détectée",
        icon: "alert-triangle",
      },
      {
        id: "a2",
        date: "19 Avril, 14:00",
        action: "Visite vétérinaire",
        icon: "user",
      },
      {
        id: "a3",
        date: "15 Avril, 10:30",
        action: "Installation de nouvelles ceintures",
        icon: "tool",
      },
    ],
    animals: [
      {
        id: "an1",
        tag: "BV-9012",
        type: "Vache",
        age: "2 ans",
        status: "Surveillance",
      },
      {
        id: "an2",
        tag: "BV-9013",
        type: "Vache",
        age: "5 ans",
        status: "Sain",
      },
      {
        id: "an3",
        tag: "BV-9014",
        type: "Veau",
        age: "6 mois",
        status: "Surveillance",
      },
    ],
  },
  4: {
    id: "4",
    name: "Sophie Dubois",
    location: "Marseille, France",
    email: "sophie.dubois@example.com",
    phone: "+33 6 45 67 89 01",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    joinDate: "12 Février 2021",
    farm: {
      name: "Ferme Méditerranée",
      size: "56 hectares",
      address: "101 Boulevard du Littoral, 13000 Marseille",
      coordinates: { lat: 43.296482, lng: 5.36978 },
    },
    stats: {
      animals: 56,
      belts: 15,
      activeMonitoring: 48,
      healthAlerts: 1,
    },
    performance: {
      healthScore: 88,
      reproductionRate: 82,
      feedEfficiency: 90,
      overallRating: 4,
    },
    recentActivity: [
      {
        id: "a1",
        date: "Aujourd'hui, 11:30",
        action: "Mise à jour du système",
        icon: "refresh-cw",
      },
      {
        id: "a2",
        date: "Hier, 15:45",
        action: "Nouvel employé formé",
        icon: "users",
      },
      {
        id: "a3",
        date: "21 Avril, 09:00",
        action: "Maintenance programmée",
        icon: "calendar",
      },
    ],
    animals: [
      {
        id: "an1",
        tag: "BV-3456",
        type: "Vache",
        age: "4 ans",
        status: "Sain",
      },
      {
        id: "an2",
        tag: "BV-3457",
        type: "Taureau",
        age: "7 ans",
        status: "Sain",
      },
      {
        id: "an3",
        tag: "BV-3458",
        type: "Vache",
        age: "3 ans",
        status: "Surveillance",
      },
    ],
  },
  5: {
    id: "5",
    name: "Thomas Leroy",
    location: "Nantes, France",
    email: "thomas.leroy@example.com",
    phone: "+33 6 56 78 90 12",
    image: "https://randomuser.me/api/portraits/men/91.jpg",
    joinDate: "8 Septembre 2020",
    farm: {
      name: "Élevage de l'Ouest",
      size: "64 hectares",
      address: "234 Rue de la Loire, 44000 Nantes",
      coordinates: { lat: 47.218371, lng: -1.553621 },
    },
    stats: {
      animals: 64,
      belts: 18,
      activeMonitoring: 60,
      healthAlerts: 0,
    },
    performance: {
      healthScore: 94,
      reproductionRate: 89,
      feedEfficiency: 86,
      overallRating: 4.5,
    },
    recentActivity: [
      {
        id: "a1",
        date: "Hier, 16:20",
        action: "Rapport trimestriel généré",
        icon: "file-text",
      },
      {
        id: "a2",
        date: "22 Avril, 10:15",
        action: "Nouvelle ceinture activée",
        icon: "plus-circle",
      },
      {
        id: "a3",
        date: "18 Avril, 14:30",
        action: "Mise à jour des données",
        icon: "database",
      },
    ],
    animals: [
      {
        id: "an1",
        tag: "BV-7890",
        type: "Vache",
        age: "5 ans",
        status: "Sain",
      },
      {
        id: "an2",
        tag: "BV-7891",
        type: "Vache",
        age: "3 ans",
        status: "Sain",
      },
      {
        id: "an3",
        tag: "BV-7892",
        type: "Veau",
        age: "8 mois",
        status: "Sain",
      },
    ],
  },
};

// Fonction utilitaire pour obtenir un éleveur par ID
export function getFarmerById(id) {
  // Convertir l'ID en string pour s'assurer de la compatibilité
  const farmerId = String(id);
  return FARMERS_DATA[farmerId] || null;
}
